services:
  manager:
    image: ghcr.io/alexpitcher/cerebro-manager:${CEREBRO_TAG:-latest}
    restart: unless-stopped
    ports:
      - "${API_PORT:-5000}:5000"
    environment:
      FLASK_ENV: ${FLASK_ENV:-production}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: ${REDIS_DB:-0}
      REDIS_JOB_TIMEOUT: ${REDIS_JOB_TIMEOUT:-30}
      REDIS_BLOCK_TIMEOUT: ${REDIS_BLOCK_TIMEOUT:-5}
      JOB_TTL_SECONDS: ${JOB_TTL_SECONDS:-3600}
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
