name: Build Windows Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r worker/gui_requirements.txt
          pip install pyinstaller

      - name: Build GUI executable
        run: |
          pyinstaller worker/build.spec

      - name: Install Inno Setup
        run: choco install innosetup --no-progress -y

      - name: Stage bundle
        shell: pwsh
        run: |
          Copy-Item worker/config.json dist/config.json -Force
          Copy-Item .env.example dist/.env.example -Force
          Copy-Item worker/BUILD.md dist/BUILD.md -Force

      - name: Build installer
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "worker\installer.iss"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cerebro-worker-windows
          path: |
            dist/CerebroWorker.exe
            dist/CerebroWorkerInstaller.exe

      - name: Create Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/CerebroWorker.exe
            dist/CerebroWorkerInstaller.exe
